site_name: Duolingo

repo_name: '2024.1-Duolingo'
repo_url: 'https://github.com/EhOMiguel/Prov-req'

docs_dir: gitpages/docs

theme:
  name: material
  language: pt-BR
  font: 
    text: Roboto
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  palette:

    # Paleta para o modo claro
    - scheme: default
      primary: green
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Modo Escuro

    # Paleta para o modo escuro
    - scheme: slate
      primary: green
      accent: light-blue
      toggle:
        icon: material/brightness-3
        name: Modo Claro

nav: 
  - Início: index.md
  - Visão Geral: visao_geral.md
  - Pré-Rastreabilidade:
    - Sobre: pre_rastreabilidade/index.md
    - Mapa mental: pre_rastreabilidade/mapaMental.md
    - Rich Pictures: pre_rastreabilidade/richPictures.md
    - Argumentações: pre_rastreabilidade/argumentacoes.md
    - Referências: pre_rastreabilidade/referencias.md
  - Elicitação:
    - Sobre: elicitacao/index.md
    - Introspecção: elicitacao/introspeccao.md
    - Resultado das técnicas de elicitação: elicitacao/result.md
    - Referências: elicitacao/referencias.md
  - Modelagem:
    - Sobre: modelagem/index.md
    - Cenários:
      - Cenário1: modelagem/cenarios/primeiro_acesso.md 
      - Cenário2: modelagem/cenarios/compartilhar_exercicio.md
      - Cenário3: modelagem/cenarios/trocar_curso.md
      - Cenário4: modelagem/cenarios/compartilhar_conquista.md
      - Cenário5: modelagem/cenarios/compartilhar_perfil.md
    - Léxicos: modelagem/lexicos.md
    - Referências: modelagem/referencias.md
  - Atas de reunião: ata_reuniao/atas.md
  - Pages:
    - Introspecção - Vinícius: pages/introspeccao_Vinicius.md

icons:
  - name: custom-favicon
    src: .icons/favicon.svg