site_name: REQ-2024.1-Duolingo

repo_name: 'REQ-2024.1-Duolingo'
repo_url: 'https://github.com/EhOMiguel/REQ-2024.1-Duolingo'

docs_dir: gitpages/docs

theme:
  name: material
  language: pt-BR
  font: 
    text: Roboto
  logo: assets/icons/logo_light.svg
  favicon: assets/icons/favicon.svg
  palette:

    # Paleta para o modo claro
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Modo Claro

    # Paleta para o modo escuro
    - scheme: slate
      primary: grey
      accent: light-green
      toggle:
        icon: material/brightness-3
        name: Modo Escuro

nav: 
  - Início: index.md
  - Visão Geral: visao_geral.md
  - Pré-Rastreabilidade:
    - Sobre: pre_rastreabilidade/index.md
    - Mapa mental: pre_rastreabilidade/mapaMental.md
    - Rich Pictures: pre_rastreabilidade/richPictures.md
    - Argumentações: pre_rastreabilidade/argumentacoes.md
    - Referências: pre_rastreabilidade/referencias.md
  - Elicitação:
    - Sobre: elicitacao/index.md
    - Introspecção:
      - Geral: elicitacao/introspeccao.md
      - Individual:
        - Arthur: elicitacao/introspeccaoIndividual/introspeccao_arthur.md
        - Bruno: elicitacao/introspeccaoIndividual/introspeccao_bruno.md
        - Felipe: elicitacao/introspeccaoIndividual/introspeccao_felipe.md
        - Gabriela: elicitacao/introspeccaoIndividual/introspeccao_gabriela.md
        - Miguel: elicitacao/introspeccaoIndividual/introspeccao_miguel.md
        - Vinícius: elicitacao/introspeccaoIndividual/introspeccao_Vinicius.md
        - Resultado: elicitacao/introspeccaoIndividual/introspeccao_resultado.md
    - Resultado das técnicas de elicitação: elicitacao/result.md
    - Referências: elicitacao/referencias.md
  - Modelagem:
    - Sobre: modelagem/index.md
    - Cenários:
      - Compartilhar Conquista: modelagem/cenarios/compartilhar_conquista.md
      - Compartilhar Exercício: modelagem/cenarios/compartilhar_exercicio.md
      - Compartilhar Perfil: modelagem/cenarios/compartilhar_perfil.md
      - Configuração Cursos: modelagem/cenarios/configuracao_cursos.md
      - Configuração Notificações: modelagem/cenarios/configuracao_notificacoes.md
      - Configuração Perfil: modelagem/cenarios/configuracao_perfil.md
      - Configuração Preferências: modelagem/cenarios/configuracao_preferencias.md
      - Configurações: modelagem/cenarios/configuracoes.md
      - Primeiro Acesso: modelagem/cenarios/primeiro_acesso.md
      - Progresso Semanal: modelagem/cenarios/progresso_semanal.md
      - Trocar Curso: modelagem/cenarios/trocar_curso.md
      - Configuração Duolingo for school: modelagem/cenarios/configiuracao_duoForSchools.md
      - Configuração Central de ajuda: modelagem/cenarios/configuracao_CentralAjuda.md
      - Configuração Privacidade: modelagem/cenarios/configuracao_privacidade.md
      - Reportar Problema: modelagem/cenarios/reportar_problema.md
    - Léxicos: modelagem/lexicos.md
    - Referências: modelagem/referencias.md
  - Atas de reunião: ata_reuniao/atas.md

# extra_javascript:
#   - js/custom.js

extra_css:
  - css/custom.css